PR for review (converted report to pdf)
marsiitr/Image-Processing-Using-FPGAs pull request #4
Opened 2022-07-26 02:17 UTC by OARSS

As suggested, the report was converted to pdf. Please review and merge if everything seems good.

2022-07-26 08:52 UTC, Nageshbansal commented
you don't have to create a new PR for changes, and you were not supposed to close the PR without asking the mentor or reviewer.

2022-07-26 08:53 UTC, OARSS commented
Sorry i did not knew that

On Tue, 26 Jul, 2022, 2:22 pm Nageshbansal, ***@***.***>
wrote:

> you don't have to create a new PR for changes, and you were not supposed
> to close the PR without asking the mentor or reviewer.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/marsiitr/Image-Processing-Using-FPGAs/pull/4#issuecomment-1195197124>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2EEAB45LBFLIWF55R7W6D3VV6RN5ANCNFSM54UISH4A>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-08-01 19:56 UTC, Nageshbansal commented
LGTM

2022-08-07 18:52 UTC, Nageshbansal commented
LGTM.
Tagging in @SanjeevKrishnan and @theobscuredev in case they have any other suggestions.

2022-08-19 12:37 UTC, SanjeevKrishnan requested changes
@OARSS @mayank4655 @jayantb007 @Rajeev-Gupta555 Repo is well structured, and looks impressive. 
In README.md, texts need to be justified.
@Nageshbansal follow this up!

2022-08-20 10:55 UTC, OARSS commented
@SanjeevKrishnan do you mean justify align the text?

2022-08-25 17:30 UTC, Nageshbansal commented
@OARSS, By justifying the text we meant the content of the README.md file should be more relevant, clean( grammar mistakes), etc.
And Let me know when you're done with changes

2026-05-24 13:06 UTC, merged